channels:
- id: "991199065196990585" # APD PF check
  duty: "Dragonsong's Reprise (Ultimate)"
  dataCentres: [Aether]
- id: "1009566968396922951" # NPS pf check 1
  duty: "Anabaseios: The Ninth Circle (Savage)"
  dataCentres: [Aether, Crystal, Primal, Dynamis]
- id: "1009567736650801293" # NPS pf check 2
  duty: "Anabaseios: The Tenth Circle (Savage)"
  dataCentres: [Aether, Crystal, Primal, Dynamis]
- id: "1009568748438556832" # NPS pf check 3
  duty: "Anabaseios: The Eleventh Circle (Savage)"
  dataCentres: [Aether, Crystal, Primal, Dynamis]
- id: "1009568848636293250"  # NPS pf check 4
  duty: "Anabaseios: The Twelfth Circle (Savage)"
  dataCentres: [Aether, Crystal, Primal, Dynamis]
- id: "1003797164222337094" # UPR ucob pf check
  duty: "The Unending Coil of Bahamut (Ultimate)"
  dataCentres: [Primal]
- id: "1003797182639525899" # UPR uwu pf check
  duty: "The Weapon's Refrain (Ultimate)"
  dataCentres: [Primal]
- id: "1003797201895571508" # UPR tea pf check
  duty: "The Epic of Alexander (Ultimate)"
  dataCentres: [Primal]
- id: "1003797214491066498" # UPR dsr pf check
  duty: "Dragonsong's Reprise (Ultimate)"
  dataCentres: [Primal]
- id: "1066846031867809894" # UPR top pf check
  duty: "The Omega Protocol (Ultimate)"
  dataCentres: [Primal]
- id: "1037081516523651132" # UDR ucob pf check
  duty: "The Unending Coil of Bahamut (Ultimate)"
  dataCentres: [Dynamis]
- id: "1037081529366630451" # UDR uwu pf check
  duty: "The Weapon's Refrain (Ultimate)"
  dataCentres: [Dynamis]
- id: "1037081703283433502" # UDR tea pf check
  duty: "The Epic of Alexander (Ultimate)"
  dataCentres: [Dynamis]
- id: "1037081714683547718" # UDR dsr pf check
  duty: "Dragonsong's Reprise (Ultimate)"
  dataCentres: [Dynamis]
- id: "1061465824780628038" # TOP aether
  duty: "The Omega Protocol (Ultimate)"
  dataCentres: [Aether]
- id: "1061465841843044393" # TOP primal
  duty: "The Omega Protocol (Ultimate)"
  dataCentres: [Primal]
- id: "1061465854748926012" # TOP crystal
  duty: "The Omega Protocol (Ultimate)"
  dataCentres: [Crystal]
- id: "1061465866039984238" # TOP dynamis
  duty: "The Omega Protocol (Ultimate)"
  dataCentres: [Dynamis]
- id: "989246195857756220" # UAR uwu-check
  duty: "The Weapon's Refrain (Ultimate)"
  dataCentres: [Aether]
- id: "989246217076736030" # UAR ucob-check
  duty: "The Unending Coil of Bahamut (Ultimate)"
  dataCentres: [Aether]
- id: "989246232994140242" # UAR tea-check
  duty: "The Epic of Alexander (Ultimate)"
  dataCentres: [Aether]
- id: "989246259359547402" # UAR dru-check
  duty: "Dragonsong's Reprise (Ultimate)"
  dataCentres: [Aether]
- id: "989246280461074512" # UAR top-check
  duty: "The Omega Protocol (Ultimate)"
  dataCentres: [Aether]
- id: "1106427289908035654" # Mala top check
  duty: "The Omega Protocol (Ultimate)"
  dataCentres: [Aether]
- id: "1106427303573065818" # Mala dsr check
  duty: "Dragonsong's Reprise (Ultimate)"
  dataCentres: [Aether]
- id: "1106427382392442941" # Mala tea check
  duty: "The Epic of Alexander (Ultimate)"
  dataCentres: [Aether]
- id: "1106427321893793853" # Mala uwu check
  duty: "The Weapon's Refrain (Ultimate)"
  dataCentres: [Aether]
- id: "1106427345746804757" # Mala ucob check
  duty: "The Unending Coil of Bahamut (Ultimate)"
  dataCentres: [Aether]
- id: "1112960917051809792" # Mala pf check 1
  duty: "Anabaseios: The Ninth Circle (Savage)"
  dataCentres: [Aether, Crystal, Primal, Dynamis]
- id: "1112960959196176474" # Mala pf check 2
  duty: "Anabaseios: The Tenth Circle (Savage)"
  dataCentres: [Aether, Crystal, Primal, Dynamis]
- id: "1112960989508403300" # Mala pf check 3
  duty: "Anabaseios: The Eleventh Circle (Savage)"
  dataCentres: [Aether, Crystal, Primal, Dynamis]
- id: "1112961011788566558"  # Mala pf check 4
  duty: "Anabaseios: The Twelfth Circle (Savage)"
  dataCentres: [Aether, Crystal, Primal, Dynamis]
- id: "1120053963673309245" # Savage Learning Academy p9s
  duty: "Anabaseios: The Ninth Circle (Savage)"
  dataCentres: [Aether, Crystal, Primal, Dynamis]
- id: "1120053976369471539" # Savage Learning Academy p10s
  duty: "Anabaseios: The Tenth Circle (Savage)"
  dataCentres: [Aether, Crystal, Primal, Dynamis]
- id: "1120053989896097882" # Savage Learning Academy p11s
  duty: "Anabaseios: The Eleventh Circle (Savage)"
  dataCentres: [Aether, Crystal, Primal, Dynamis]
- id: "1120054005419221063" # Savage Learning Academy p12s
  duty: "Anabaseios: The Twelfth Circle (Savage)"
  dataCentres: [Aether, Crystal, Primal, Dynamis]
- id: "1168327640638296065" # golden sheep top check
  duty: "The Omega Protocol (Ultimate)"
  dataCentres: [Aether, Crystal, Primal, Dynamis]
- id: "1168327674708631633" # golden sheep dsr check
  duty: "Dragonsong's Reprise (Ultimate)"
  dataCentres: [Aether, Crystal, Primal, Dynamis]
- id: "1168327701694783498" # golden sheep tea check
  duty: "The Epic of Alexander (Ultimate)"
  dataCentres: [Aether, Crystal, Primal, Dynamis]
- id: "1168327733357576283" # golden sheep uwu check
  duty: "The Weapon's Refrain (Ultimate)"
  dataCentres: [Aether, Crystal, Primal, Dynamis]
- id: "1168327757374181446" # golden sheep ucob check
  duty: "The Unending Coil of Bahamut (Ultimate)"
  dataCentres: [Aether, Crystal, Primal, Dynamis]
- id: "1172326220352987257" # raidingway aether ucob check
  duty: "The Unending Coil of Bahamut (Ultimate)"
  dataCentres: [Aether]
- id: "1172326251118198814" # raidingway aether uwu check
  duty: "The Weapon's Refrain (Ultimate)"
  dataCentres: [Aether]
- id: "1172326284257407027" # raidingway aether tea check
  duty: "The Epic of Alexander (Ultimate)"
  dataCentres: [Aether]
- id: "1172326306847920150" # raidingway aether dsr check
  duty: "Dragonsong's Reprise (Ultimate)"
  dataCentres: [Aether]
- id: "1172326326645051412" # raidingway aether top check
  duty: "The Omega Protocol (Ultimate)"
  dataCentres: [Aether]
- id: "1172327931767427072" # raidingway aether p9s check
  duty: "Anabaseios: The Ninth Circle (Savage)"
  dataCentres: [Aether]
- id: "1172327947668045885" # raidingway aether p10s check
  duty: "Anabaseios: The Tenth Circle (Savage)"
  dataCentres: [Aether]
- id: "1172327961622487070" # raidingway aether p11s check
  duty: "Anabaseios: The Eleventh Circle (Savage)"
  dataCentres: [Aether]
- id: "1172327983952953445" # raidingway aether p12s check
  duty: "Anabaseios: The Twelfth Circle (Savage)"
  dataCentres: [Aether]
- id: "1172328090836406415" # raidingway aether zeromus
  duty: "The Abyssal Fracture (Extreme)"
  dataCentres: [Aether]
- id: "1174341288678662215" # raidingway aether king thordan
  duty: "The Singularity Reactor (Unreal)"
  dataCentres: [Aether]
- id: "1172330360474968084" # raidingway crystal ucob check
  duty: "The Unending Coil of Bahamut (Ultimate)"
  dataCentres: [Crystal]
- id: "1172330411104407642" # raidingway crystal uwu check
  duty: "The Weapon's Refrain (Ultimate)"
  dataCentres: [Crystal]
- id: "1172330431958499410" # raidingway crystal tea check
  duty: "The Epic of Alexander (Ultimate)"
  dataCentres: [Crystal]
- id: "1172330445300568105" # raidingway crystal dsr check
  duty: "Dragonsong's Reprise (Ultimate)"
  dataCentres: [Crystal]
- id: "1172330456289652858" # raidingway crystal top check
  duty: "The Omega Protocol (Ultimate)"
  dataCentres: [Crystal]
- id: "1172330512891781210" # raidingway crystal p9s check
  duty: "Anabaseios: The Ninth Circle (Savage)"
  dataCentres: [Crystal]
- id: "1172330529698353322" # raidingway crystal p10s check
  duty: "Anabaseios: The Tenth Circle (Savage)"
  dataCentres: [Crystal]
- id: "1172330540117016597" # raidingway crystal p11s check
  duty: "Anabaseios: The Eleventh Circle (Savage)"
  dataCentres: [Crystal]
- id: "1172330551261265951" # raidingway crystal p12s check
  duty: "Anabaseios: The Twelfth Circle (Savage)"
  dataCentres: [Crystal]
- id: "1172330629749293169" # raidingway crystal zeromus
  duty: "The Abyssal Fracture (Extreme)"
  dataCentres: [Crystal]
- id: "1174341478194102282" # raidingway crystal king thordan
  duty: "The Singularity Reactor (Unreal)"
  dataCentres: [Crystal]
- id: "1172330964572176386" # raidingway dynamis ucob check
  duty: "The Unending Coil of Bahamut (Ultimate)"
  dataCentres: [Dynamis]
- id: "1172330991587692585" # raidingway dynamis uwu check
  duty: "The Weapon's Refrain (Ultimate)"
  dataCentres: [Dynamis]
- id: "1172331006292938802" # raidingway dynamis tea check
  duty: "The Epic of Alexander (Ultimate)"
  dataCentres: [Dynamis]
- id: "1172331029026062357" # raidingway dynamis dsr check
  duty: "Dragonsong's Reprise (Ultimate)"
  dataCentres: [Dynamis]
- id: "1172331043802599434" # raidingway dynamis top check
  duty: "The Omega Protocol (Ultimate)"
  dataCentres: [Dynamis]
- id: "1172331185343582208" # raidingway dynamis p9s check
  duty: "Anabaseios: The Ninth Circle (Savage)"
  dataCentres: [Dynamis]
- id: "1172331212698832907" # raidingway dynamis p10s check
  duty: "Anabaseios: The Tenth Circle (Savage)"
  dataCentres: [Dynamis]
- id: "1172331227898978334" # raidingway dynamis p11s check
  duty: "Anabaseios: The Eleventh Circle (Savage)"
  dataCentres: [Dynamis]
- id: "1172331199751008286" # raidingway dynamis p12s check
  duty: "Anabaseios: The Twelfth Circle (Savage)"
  dataCentres: [Dynamis]
- id: "1172331314461016114" # raidingway dynamis zeromus
  duty: "The Abyssal Fracture (Extreme)"
  dataCentres: [Dynamis]
- id: "1174342061915389992" # raidingway dynamis king thordan
  duty: "The Singularity Reactor (Unreal)"
  dataCentres: [Dynamis]
- id: "1172332940781441104" # raidingway primal ucob check
  duty: "The Unending Coil of Bahamut (Ultimate)"
  dataCentres: [Primal]
- id: "1172332955478274118" # raidingway primal uwu check
  duty: "The Weapon's Refrain (Ultimate)"
  dataCentres: [Primal]
- id: "1172332996104298587" # raidingway primal tea check
  duty: "The Epic of Alexander (Ultimate)"
  dataCentres: [Primal]
- id: "1172333014538276945" # raidingway primal dsr check
  duty: "Dragonsong's Reprise (Ultimate)"
  dataCentres: [Primal]
- id: "1172333025942585374" # raidingway primal top check
  duty: "The Omega Protocol (Ultimate)"
  dataCentres: [Primal]
- id: "1172333109589585920" # raidingway primal p9s check
  duty: "Anabaseios: The Ninth Circle (Savage)"
  dataCentres: [Primal]
- id: "1172333119626543166" # raidingway primal p10s check
  duty: "Anabaseios: The Tenth Circle (Savage)"
  dataCentres: [Primal]
- id: "1172333133035753553" # raidingway primal p11s check
  duty: "Anabaseios: The Eleventh Circle (Savage)"
  dataCentres: [Primal]
- id: "1172333144511352832" # raidingway primal p12s check
  duty: "Anabaseios: The Twelfth Circle (Savage)"
  dataCentres: [Primal]
- id: "1172333202476634142" # raidingway primal zeromus
  duty: "The Abyssal Fracture (Extreme)"
  dataCentres: [Primal]
- id: "1174342335404986469" # raidingway primal king thordan
  duty: "The Singularity Reactor (Unreal)"
  dataCentres: [Primal]
