channels:
- id: "991199065196990585" # APD PF check
  duty: "Dragonsong's Reprise (Ultimate)"
  dataCentres: [Aether]
- id: "1009566968396922951" # NPS pf check 1
  duty: "Asphodelos: The First Circle (Savage)"
  dataCentres: [Aether, Crystal, Primal]
- id: "1009567736650801293" # NPS pf check 2
  duty: "Asphodelos: The Second Circle (Savage)"
  dataCentres: [Aether, Crystal, Primal]
- id: "1009568748438556832" # NPS pf check 3
  duty: "Asphodelos: The Third Circle (Savage)"
  dataCentres: [Aether, Crystal, Primal]
- id: "1009568848636293250"  # NPS pf check 4
  duty: "Asphodelos: The Fourth Circle (Savage)"
  dataCentres: [Aether, Crystal, Primal]
- id: "1003797164222337094" # UPR ucob pf check
  duty: "The Unending Coil of Bahamut (Ultimate)"
  dataCentres: [Primal]
- id: "1003797182639525899" # UPR uwu pf check
  duty: "The Weapon's Refrain (Ultimate)"
  dataCentres: [Primal]
- id: "1003797201895571508" # UPR tea pf check
  duty: "The Epic of Alexander (Ultimate)"
  dataCentres: [Primal]
- id: "1003797214491066498" # UPR dsr pf check
  duty: "Dragonsong's Reprise (Ultimate)"
  dataCentres: [Primal]
