channels:
- id: "991199065196990585" # APD PF check
  duty: "Dragonsong's Reprise (Ultimate)"
  dataCentres: [Aether]
- id: "1009566968396922951" # NPS pf check 1
  duty: "Abyssos: The Ninth Circle (Savage)"
  dataCentres: [Aether, Crystal, Primal, Dynamis]
- id: "1009567736650801293" # NPS pf check 2
  duty: "Abyssos: The Tenth Circle (Savage)"
  dataCentres: [Aether, Crystal, Primal, Dynamis]
- id: "1009568748438556832" # NPS pf check 3
  duty: "Abyssos: The Eleventh Circle (Savage)"
  dataCentres: [Aether, Crystal, Primal, Dynamis]
- id: "1009568848636293250"  # NPS pf check 4
  duty: "Abyssos: The Twelfth Circle (Savage)"
  dataCentres: [Aether, Crystal, Primal, Dynamis]
- id: "1003797164222337094" # UPR ucob pf check
  duty: "The Unending Coil of Bahamut (Ultimate)"
  dataCentres: [Primal]
- id: "1003797182639525899" # UPR uwu pf check
  duty: "The Weapon's Refrain (Ultimate)"
  dataCentres: [Primal]
- id: "1003797201895571508" # UPR tea pf check
  duty: "The Epic of Alexander (Ultimate)"
  dataCentres: [Primal]
- id: "1003797214491066498" # UPR dsr pf check
  duty: "Dragonsong's Reprise (Ultimate)"
  dataCentres: [Primal]
- id: "1066846031867809894" # UPR top pf check
  duty: "The Omega Protocol (Ultimate)"
  dataCentres: [Primal]
- id: "1037081516523651132" # UDR ucob pf check
  duty: "The Unending Coil of Bahamut (Ultimate)"
  dataCentres: [Dynamis]
- id: "1037081529366630451" # UDR uwu pf check
  duty: "The Weapon's Refrain (Ultimate)"
  dataCentres: [Dynamis]
- id: "1037081703283433502" # UDR tea pf check
  duty: "The Epic of Alexander (Ultimate)"
  dataCentres: [Dynamis]
- id: "1037081714683547718" # UDR dsr pf check
  duty: "Dragonsong's Reprise (Ultimate)"
  dataCentres: [Dynamis]
- id: "1061465824780628038" # TOP aether
  duty: "The Omega Protocol (Ultimate)"
  dataCentres: [Aether]
- id: "1061465841843044393" # TOP primal
  duty: "The Omega Protocol (Ultimate)"
  dataCentres: [Primal]
- id: "1061465854748926012" # TOP crystal
  duty: "The Omega Protocol (Ultimate)"
  dataCentres: [Crystal]
- id: "1061465866039984238" # TOP dynamis
  duty: "The Omega Protocol (Ultimate)"
  dataCentres: [Dynamis]
- id: "989246280461074512" # UAR top-check
  duty: "The Omega Protocol (Ultimate)"
  dataCentres: [Aether]
- id: "1106427289908035654" # Mala top check
  duty: "The Omega Protocol (Ultimate)"
  dataCentres: [Aether]
- id: "1106427303573065818" # Mala dsr check
  duty: "Dragonsong's Reprise (Ultimate)"
  dataCentres: [Aether]
- id: "1106427382392442941" # Mala tea check
  duty: "The Epic of Alexander (Ultimate)"
  dataCentres: [Aether]
- id: "1106427321893793853" # Mala uwu check
  duty: "The Weapon's Refrain (Ultimate)"
  dataCentres: [Aether]
- id: "1106427345746804757" # Mala ucob check
  duty: "The Unending Coil of Bahamut (Ultimate)"
  dataCentres: [Aether]
- id: "1106508173717807144" # reprise41 top check
  duty: "The Omega Protocol (Ultimate)"
  dataCentres: [Aether]
- id: "1106508141056761976" # reprise41 dsr check
  duty: "Dragonsong's Reprise (Ultimate)"
  dataCentres: [Aether]
- id: "1106514690680561675" # reprise41 tea check
  duty: "The Epic of Alexander (Ultimate)"
  dataCentres: [Aether]
- id: "1106514761874685952" # reprise41 uwu check
  duty: "The Weapon's Refrain (Ultimate)"
  dataCentres: [Aether]
- id: "1106514724587307048" # reprise41 ucob check
  duty: "The Unending Coil of Bahamut (Ultimate)"
  dataCentres: [Aether]
